import lsolve
lsolve.error.demo(30)
